PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

ifeq ($(CREATIVE_VERSION_APPEND_TIME_OF_DAY),true)
    CREATIVE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    CREATIVE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set CREATIVE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef CREATIVE_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "CREATIVE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^CREATIVE_||g')
        CREATIVE_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(CREATIVE_BUILDTYPE)),)
    CREATIVE_BUILDTYPE := UNOFFICIAL
    CREATIVE_EXTRAVERSION :=
endif

ifeq ($(CREATIVE_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        CREATIVE_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

CREATIVE_VERSION_SUFFIX := $(CREATIVE_BUILD_DATE)-$(CREATIVE_BUILDTYPE)$(CREATIVE_EXTRAVERSION)-$(CREATIVE_BUILD)

# Internal version
CREATIVE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CREATIVE_VERSION_SUFFIX)

# Display version
CREATIVE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(CREATIVE_VERSION_SUFFIX)
